"""Production bridge to the legacy row-joint monospace lattice decoder.

What this module does
---------------------
The repository's only recognizer that has ever produced structurally
coherent machine text on live screenshots is the row-joint decoder in
``scripts/decode_monospace_rows.py``.  It learns glyph templates from
repeated shapes inside the SOURCE screenshot itself (leave-one-out, so a
cell never validates itself), scores whole rows with overlapping windows,
charges a cost for unexplained ink, and emits ``?`` for low-margin cells
instead of guessing.  Horse attempts 001-064 were generated by it.

That decoder was de-authorized as an *acceptance* path because coherent
structure is not glyph identity (see the failure log: unknown/low-margin
rows, small alphabet).  This module brings its capability back as
PROPOSAL EVIDENCE ONLY, behind the production ``transcribe()`` gates:

* the decoder body stays in ``scripts/decode_monospace_rows.py`` — this
  module loads that single owner and never copies its logic;
* a decode requires a hash-bound calibration whose ``source_sha256``
  matches the image being decoded (calibrations live in the tracked
  parity attempt history and are immutable);
* the output preserves every ``?`` cell; downstream selection must refuse
  to write a candidate from any text that still contains ``?``.

Why the calibration comes from the tracked history
--------------------------------------------------
The geometry router currently cannot prove the lattice for the very
sources this decoder handles (the horse source routes ``shaped_runs``
with ``pitch_proven`` false — see the 2026-08-05 failure-log entry on
mode misassignment).  The legacy calibrations are source-hash-bound
measurements reviewed during the attempt history, so using them keeps the
decode deterministic and source-derived without trusting the unproven
mode label.  When the router later proves lattices itself, that proof can
replace this lookup at a single seam: ``resolve_calibration``.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from functools import lru_cache
from pathlib import Path
from typing import Any, Mapping

# Repository root, derived from this file's location so behaviour does not
# depend on the caller's current directory.
_REPOSITORY_ROOT = Path(__file__).resolve().parents[3]

# Single owner of the decode logic.  This module intentionally has no
# fallback path: if the script is missing, the bridge refuses to decode.
_LEGACY_DECODER_PATH = _REPOSITORY_ROOT / "scripts" / "decode_monospace_rows.py"

# Where hash-bound calibrations are recorded by the immutable attempt
# history.  Only files named calibration.json inside an attempt directory
# are considered; nothing else may act as a calibration source.
_PARITY_ROOT = _REPOSITORY_ROOT / "tracked" / "LateLetterResearch" / "transcription-parity"

ADAPTER_NAME = "row-joint-lattice"


@lru_cache(maxsize=1)
def _legacy_module():
    """Load the legacy decoder script as a module exactly once.

    The module must be registered in ``sys.modules`` before execution so
    its frozen dataclasses can locate their own module namespace.
    """

    if not _LEGACY_DECODER_PATH.exists():
        raise FileNotFoundError(f"row-joint decoder missing: {_LEGACY_DECODER_PATH}")
    spec = importlib.util.spec_from_file_location("lateletter_legacy_row_joint", _LEGACY_DECODER_PATH)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load row-joint decoder from {_LEGACY_DECODER_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["lateletter_legacy_row_joint"] = module
    spec.loader.exec_module(module)
    return module


def decoder_version() -> str:
    """Expose the legacy decoder's own version string for receipts."""

    return str(getattr(_legacy_module(), "DECODER_VERSION", "unknown"))


@lru_cache(maxsize=1)
def _calibration_index() -> tuple[tuple[str, str], ...]:
    """Map every tracked calibration to its bound source hash.

    Returns ``(source_sha256, calibration_path)`` pairs sorted by path so
    the scan order — and therefore every downstream choice — is
    deterministic.  The scan is cached; calibrations are immutable attempt
    artifacts, so a stale cache cannot occur within one process run.
    """

    pairs: list[tuple[str, str]] = []
    if not _PARITY_ROOT.exists():
        return ()
    for path in sorted(_PARITY_ROOT.glob("*/attempts/*/calibration.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            # An unreadable calibration is skipped, never guessed at.
            continue
        digest = str(payload.get("source_sha256", ""))
        if len(digest) == 64:
            pairs.append((digest, str(path)))
    return tuple(pairs)


def resolve_calibration(source_sha256: str) -> tuple[dict[str, Any], str] | None:
    """Return the newest tracked calibration bound to ``source_sha256``.

    "Newest" means the lexicographically last attempt path, which follows
    the zero-padded attempt numbering convention of the parity history.
    Returns ``None`` when no calibration is bound to this exact source
    hash — the caller must then treat row-joint decode as unavailable
    rather than inventing a lattice.
    """

    matches = [item for item in _calibration_index() if item[0] == source_sha256]
    if not matches:
        return None
    chosen_path = matches[-1][1]
    payload = json.loads(Path(chosen_path).read_text(encoding="utf-8"))
    return payload, chosen_path


def decode_rows_with_calibration(source_png: Path, calibration: Mapping[str, Any]) -> dict[str, Any]:
    """Run the legacy row-joint decode for one source under one calibration.

    The calibration's ``source_sha256`` must match the image bytes; a
    mismatch raises instead of decoding, because a calibration measured on
    different bytes proves nothing about this image.  The returned mapping
    carries the decoded rows with every ``?`` preserved, plus the evidence
    counts a selector needs to judge the result.
    """

    module = _legacy_module()
    actual = module.sha256(source_png)
    bound = str(calibration.get("source_sha256", ""))
    if actual != bound:
        raise ValueError(f"calibration is bound to {bound[:12]}, source bytes are {actual[:12]}")
    cells = module.segment(source_png, dict(calibration))
    templates = module.build_templates(cells)
    grid = calibration["grid"]
    columns, rows = int(grid["columns"]), int(grid["rows"])
    decoded_all: list[str] = []
    confidences: list[float] = []
    for row in range(rows):
        row_cells = cells[row * columns : (row + 1) * columns]
        decoded, row_confidences, _meta = module.decode_row(row_cells, templates)
        decoded_all.extend(decoded)
        confidences.extend(row_confidences)
    # The consensus pass may replace a ``?`` only when repeated topology
    # across the screenshot agrees; it never invents an unseen glyph.
    decoded_all = module.apply_repeated_topology_consensus(cells, decoded_all, confidences, columns)
    lines = ["".join(decoded_all[row * columns : (row + 1) * columns]).rstrip() for row in range(rows)]
    unknown = str(getattr(module, "UNKNOWN", "?"))
    unknown_cells = sum(1 for glyph in decoded_all if glyph == unknown)
    return {
        "adapter": ADAPTER_NAME,
        "decoder_version": decoder_version(),
        "rows": lines,
        "text": "\n".join(lines).rstrip("\n"),
        "columns": columns,
        "row_count": rows,
        "cell_count": len(decoded_all),
        "unknown_cells": unknown_cells,
        "unknown_marker": unknown,
        "source_sha256": actual,
        "template_glyphs": sorted(templates.keys()),
    }


def decode_for_source(source_png: Path) -> dict[str, Any] | None:
    """Decode ``source_png`` if a tracked hash-bound calibration exists.

    This is the single entry the production pipeline calls.  It returns
    ``None`` when no calibration is bound to the source — absence of a
    lattice measurement is a typed unavailability, not an error — and the
    decode result (with calibration provenance attached) otherwise.
    """

    module = _legacy_module()
    found = resolve_calibration(module.sha256(source_png))
    if found is None:
        return None
    calibration, calibration_path = found
    result = decode_rows_with_calibration(source_png, calibration)
    result["calibration_path"] = calibration_path
    result["calibration_sha256"] = module.sha256(Path(calibration_path))
    return result
