"""Canonical evidence records for screenshot-to-Unicode text-art recovery.

This package deliberately contains records and hash-bound persistence helpers,
not a recognizer.  Recognition adapters may propose evidence, but only records
validated here can be used by the later candidate writer.
"""

from .model import (
    CandidateBundle,
    CellLattice,
    ComparisonReceipt,
    GateReport,
    GeometryDecision,
    GraphemeCandidate,
    InkComponent,
    NormalizationReceipt,
    OperatorReviewReceipt,
    OwnershipAssignment,
    RecognitionProposal,
    RowBand,
    RunAnchor,
    SourceReceipt,
    VisualRun,
)
from .schema import canonical_bytes, canonical_json, record_from_dict, record_to_dict
from .versions import MODULE_VERSION, SCHEMA_VERSION
from .attempts import (
    AttemptError,
    create_attempt,
    read_record,
    verify_candidate_bundle,
    write_candidate_bundle,
    write_record,
)
from .pipeline import accept, transcribe
from .unicode_profile import GraphemeRecord, UnicodeRunError, inspect_row, require_shaping_profile, segment_graphemes
from .corpus import CorpusError, validate_corpus
from .recognition import (
    CapabilityProfile,
    EmojiAtlasAdapter,
    EnvironmentLock,
    FixedLatticeStructuralAdapter,
    StructuralUnicodeRowAdapter,
    UnicodeTemplateRunAdapter,
    IndependentOfflineAdapter,
    ModelArtifact,
    PaddleOCROfflineAdapter,
    ProposalSet,
    Recognizer,
    TesseractOfflineAdapter,
    align_logical_text_to_run,
    benchmark_offline_ensemble,
    benchmark_release_coverage,
    build_environment_lock,
    inventory_adapters,
    verify_model_cache,
    jointly_score_geometry_hypotheses,
    jointly_decode_geometry_text,
)
from .geometry import (
    GeometryEvidenceBundle,
    RecognitionInputBuilder,
    build_geometry_evidence,
    build_recognition_hypothesis_inputs,
    build_recognition_inputs,
    recover_geometry,
    route_raster_geometry,
)

__all__ = [
    "CandidateBundle",
    "CellLattice",
    "ComparisonReceipt",
    "GateReport",
    "GeometryDecision",
    "GraphemeCandidate",
    "InkComponent",
    "NormalizationReceipt",
    "OperatorReviewReceipt",
    "OwnershipAssignment",
    "RecognitionProposal",
    "RowBand",
    "RunAnchor",
    "SourceReceipt",
    "VisualRun",
    "canonical_bytes",
    "canonical_json",
    "record_from_dict",
    "record_to_dict",
    "MODULE_VERSION",
    "SCHEMA_VERSION",
    "AttemptError",
    "create_attempt",
    "read_record",
    "verify_candidate_bundle",
    "write_record",
    "transcribe",
    "accept",
    "write_candidate_bundle",
    "GraphemeRecord",
    "UnicodeRunError",
    "inspect_row",
    "require_shaping_profile",
    "segment_graphemes",
    "CorpusError",
    "validate_corpus",
    "CapabilityProfile",
    "EmojiAtlasAdapter",
    "EnvironmentLock",
    "FixedLatticeStructuralAdapter",
    "StructuralUnicodeRowAdapter",
    "UnicodeTemplateRunAdapter",
    "IndependentOfflineAdapter",
    "ModelArtifact",
    "PaddleOCROfflineAdapter",
    "ProposalSet",
    "Recognizer",
    "TesseractOfflineAdapter",
    "align_logical_text_to_run",
    "benchmark_offline_ensemble",
    "benchmark_release_coverage",
    "build_environment_lock",
    "inventory_adapters",
    "verify_model_cache",
    "jointly_score_geometry_hypotheses",
    "jointly_decode_geometry_text",
    "GeometryEvidenceBundle",
    "RecognitionInputBuilder",
    "build_geometry_evidence",
    "build_recognition_hypothesis_inputs",
    "build_recognition_inputs",
    "recover_geometry",
    "route_raster_geometry",
]
