#!/usr/bin/env python3
"""Derive the v2 garden atlas from the v1 atlas, deterministically.

WHY THIS EXISTS
---------------
Atlas v2 adds a proportional presentation profile, a per-asset drawing anchor,
and a required record of where each drawing came from. Every one of the v1
atlas's 26 assets still needs to exist in v2, so the migration is mechanical for
all of them except the assets being deliberately re-owned.

Writing it as a script rather than editing JSON by hand matters because the
result has to be reproducible: running this twice on the same v1 atlas must
produce byte-identical output, so that a difference in the committed v2 atlas
always means a real change rather than an editing accident.

WHAT IT HONESTLY RECORDS
------------------------
The v1 atlas contains no artwork. All 26 of its assets are a single character in
a 1x1 box, and only the `ascii-safe` profile is populated -- `fixture.bench` is
the string "=", `fixture.pond` is "~". Nothing was ever drawn.

So the migration does NOT claim lineage it cannot support. Every carried-over
asset is marked with a `placeholder` source, which is what it is. Only assets
that are genuinely migrated from real artwork get a real lineage, and right now
that is exactly one: the bench.

WHY cell_box CAN GROW SAFELY
----------------------------
`cell_box` is the extent of the DRAWING, not the object's occupancy. Nothing
outside `atlas.py` reads it -- collision, placement and hit identity all come
from the world model's own integer footprints and hotspots. Growing the bench's
box from 1x1 to 14x4 therefore changes what is painted and nothing about what
the object does or which cells it blocks.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

# Identifies the code that produced the atlas. Bump this whenever the migration
# logic changes in a way that alters output, so that a regenerated atlas can be
# told apart from a hand-edited one.
GENERATOR_VERSION = "atlas-migrate-2"

# The profile name, imported rather than repeated so the script and the compiler
# cannot disagree about its spelling.
from lateletter.garden.atlas import PROPORTIONAL_PROFILE  # noqa: E402

# The exact runtime font contract for the proportional profile.
#
# Row strings are meaningless without it: their on-screen width is discovered
# by measuring them in this font, so measuring them in another would misalign
# every stroke.
#
# Every field is required, and every field is asserted against the stylesheet
# in `viewer-bnw.html` and against the bundled file itself by tests. A family
# name alone is NOT sufficient -- glyph advances differ by weight and by style
# within one family, so weight and style are part of the contract, and letter
# spacing is named explicitly because any tracking would shift every advance.
#
# `family` is a product-owned name declared by an `@font-face` rule pointing at
# `resource`. It deliberately names no fallback: a fallback would paint the art
# at advances it was never measured against, which is the exact defect this
# contract closes. Absence of the face is handled by an explicit degraded mode.
#
# Generated by scripts/build_garden_font.py; `resource_sha256` is that build's
# output hash and changes whenever the font is regenerated.
PROPORTIONAL_FONT = {
    "family": "LateLetter Garden",
    "size_px": 15,
    "line_height_px": 17,
    "weight": 400,
    "style": "normal",
    "letter_spacing": "normal",
    "resource": "web/fonts/lateletter-garden.woff",
    "resource_sha256": (
        "f6be01765d77f1045d4a098e907219975536ae6403ee8b4dc9928e8f7bce1780"
    ),
}

# Where the drawn artwork lives. Kept in its own module because it is content,
# edited on artistic grounds, whereas this file is the mechanical transform.
from garden_fixture_art import fixture_profiles  # noqa: E402


def placeholder_lineage(asset_id: str) -> dict[str, Any]:
    """Record that a carried-over asset has no drawn artwork behind it.

    Stating this explicitly is the point. A missing lineage field would read as
    an oversight; a `placeholder` lineage reads as an accurate description of an
    asset that is one character in a box and has never been drawn or reviewed.
    """
    return {
        "source": "placeholder",
        "note": (
            f"{asset_id} was carried from atlas v1 unchanged. v1 holds no artwork: "
            "every asset is a single glyph in a 1x1 box. This asset still needs to "
            "be drawn and individually reviewed."
        ),
    }


def drawn_asset(v1_asset: dict[str, Any], drawing: dict[str, Any]) -> dict[str, Any]:
    """Build a v2 asset around newly drawn artwork.

    The asset keeps its v1 identity -- same id, label, description and hotspots,
    so nothing about what it DOES changes -- and replaces its single placeholder
    glyph with a real picture in both profiles.

    :param v1_asset: The asset as it appears in the v1 atlas.
    :param drawing: The entry from `garden_fixture_art.fixture_profiles`.
    :returns: The v2 asset object.
    """
    ascii_rows = drawing["ascii"]
    proportional_rows = drawing["proportional"]
    ascii_frames = drawing.get("ascii_frames", (ascii_rows,))
    proportional_frames = drawing.get("proportional_frames", (proportional_rows,))
    frame_ticks = int(drawing.get("frame_ticks", 1))

    height = len(ascii_rows)
    width = len(ascii_rows[0])
    if len(proportional_rows) != height:
        raise ValueError(
            f"{v1_asset['id']}: both profiles must have the same row count, "
            f"got {height} ascii and {len(proportional_rows)} proportional"
        )

    # The anchor's row is always the last one: fixtures stand on the ground, and
    # the bottom row is what touches it. Only the column varies per drawing,
    # since a shape's visual centre is rarely its arithmetic middle.
    anchor_column = int(drawing["anchor_column"])
    if not 0 <= anchor_column < width:
        raise ValueError(f"{v1_asset['id']}: anchor column {anchor_column} outside width {width}")

    return {
        "id": v1_asset["id"],
        "kind": v1_asset["kind"],
        "label": v1_asset["label"],
        "description": v1_asset["description"],
        "cell_box": [width, height],
        "anchor": [anchor_column, height - 1],
        "profiles": {
            "ascii-safe": {
                "idle": [
                    {"ticks": frame_ticks, "cells": [list(row) for row in frame]}
                    for frame in ascii_frames
                ],
            },
            "browser-proportional": {
                "idle": [
                    {
                        "ticks": frame_ticks,
                        "rows": list(frame),
                        **({"accents": drawing["accents"]} if drawing.get("accents") else {}),
                    }
                    for frame in proportional_frames
                ],
            },
        },
        "hotspots": v1_asset["hotspots"],
        "tags": v1_asset.get("tags", []),
        "art_lineage": {
            "source": "drawn for LateLetter",
            "tradition": "ascii/shift-jis",
            # The canonical stroke graph both profiles realise. Recorded on the
            # asset because it is the thing under review: a reviewer judging
            # whether a drawing reads is judging whether these parts are
            # legible, not whether particular characters were chosen.
            "structure": [
                {"part": part, "role": role} for part, role in drawing["structure"]
            ],
            "material": drawing["material"],
            "affordance": drawing["affordance"],
            "references": [
                "FL-4208 morphology contract (density, openness, stroke continuity,"
                " terminal shape, interior voids, baseline anchoring, scale survival)",
                "FL-4512 NPR bibliography; Benard et al. Active Strokes -- persistent"
                " curve topology kept separate from the stylization path",
            ],
            "note": drawing["note"],
            # Provenance only. The current release verdict has one owner:
            # docs/garden-asset-acceptance.json. Keeping this receipt nested
            # and explicitly non-authoritative prevents historical sign-off
            # under the old renderer being mistaken for current acceptance.
            "historical_review": {
                "verdict": drawing["historical_review"]["verdict"],
                "round": drawing["historical_review"]["round"],
                "quote": drawing["historical_review"]["quote"],
                "authoritative": False,
                "superseded_by": "docs/garden-asset-acceptance.json",
            },
            # A requirement the review raised that the ART cannot satisfy --
            # a gap in the model rather than in the drawing. Carried on the
            # asset so it travels with the thing it constrains, instead of
            # living only in a document nobody opens when they edit the atlas.
            # Absent on assets with no such requirement, rather than empty.
            **(
                {"pending_requirement": drawing["pending_requirement"]}
                if drawing.get("pending_requirement") else {}
            ),
            # Recorded explicitly: the browser's old tables were not migrated,
            # they were discarded. Anyone comparing this against the previous
            # appearance should expect it to differ.
            "supersedes": "browser-local FIXTURE_DECOR and STARTER_FIXTURE_ART",
        },
    }


def carry_asset(v1_asset: dict[str, Any]) -> dict[str, Any]:
    """Carry a v1 asset into v2 unchanged apart from the newly required fields.

    Artwork is not invented here. The asset keeps its single-glyph profile
    exactly as it was; it gains only an anchor and an honest lineage.
    """
    asset = dict(v1_asset)
    box = asset["cell_box"]
    # A 1x1 asset can only be anchored at its one cell. For anything larger the
    # bottom-centre is the sensible default, matching the bench's reasoning.
    asset["anchor"] = [(box[0] - 1) // 2, box[1] - 1]
    asset["art_lineage"] = placeholder_lineage(asset["id"])
    return asset


def migrate(v1: dict[str, Any]) -> dict[str, Any]:
    """Produce the whole v2 atlas from a validated v1 atlas."""
    assets = []
    for v1_asset in v1["assets"]:
        # Fixtures are addressed by catalog id, which is the asset id minus its
        # `fixture.` prefix. An asset with no drawing yet is carried unchanged
        # and stays honestly marked as a placeholder.
        catalog_id = v1_asset["id"].split(".", 1)[-1]
        drawing = fixture_profiles(catalog_id) if v1_asset["id"].startswith("fixture.") else None
        if drawing is not None:
            assets.append(drawn_asset(v1_asset, drawing))
        else:
            assets.append(carry_asset(v1_asset))

    return {
        "version": 2,
        "id": "garden-atlas-2",
        "generator_version": GENERATOR_VERSION,
        "unicode_version": v1["unicode_version"],
        # The four inherited profiles are unchanged and remain cell-based; the
        # fifth is the measured one.
        "profiles": [*v1["profiles"], "browser-proportional"],
        "fonts": {"browser-proportional": PROPORTIONAL_FONT},
        # Semantic vocabulary is about meaning, not pictures, so it crosses the
        # version boundary untouched.
        "semantic_tokens": v1["semantic_tokens"],
        "connected_tiles": v1["connected_tiles"],
        "assets": assets,
    }


def emit_browser_art_module(v2: dict[str, Any]) -> str:
    """Render the atlas's proportional assets as a browser ES module.

    WHY A GENERATED MODULE RATHER THAN A FETCH
    ------------------------------------------
    The browser renderer has no bundler and no build step; it is loaded as plain
    ES modules. Reading `atlas.v2.json` at runtime would mean an asynchronous
    fetch on the render path, a second failure mode when it 404s, and an ordering
    problem where the first frame paints before the art arrives.

    Generating a module sidesteps all of that while keeping the atlas the single
    author. This file is derived, never edited: a test asserts it still matches
    the atlas, so the two cannot drift apart without something going red.

    :param v2: The migrated atlas.
    :returns: JavaScript source text.
    """
    proportional = {
        asset["id"]: {
            "anchor": asset["anchor"],
            "cell_box": asset["cell_box"],
            "states": {
                state: [
                    {
                        "ticks": frame["ticks"],
                        "rows": frame["rows"],
                        # Present only when the asset carries an authored
                        # narrow-viewport drawing; absent otherwise, so the
                        # renderer can tell "no compact art" from "same art".
                        **({"compact_rows": frame["compact_rows"]}
                           if "compact_rows" in frame else {}),
                        **({"accents": frame["accents"]}
                           if "accents" in frame else {}),
                    }
                    for frame in frames
                ]
                for state, frames in asset["profiles"][PROPORTIONAL_PROFILE].items()
            },
        }
        for asset in v2["assets"]
        if PROPORTIONAL_PROFILE in asset["profiles"]
    }

    body = json.dumps(proportional, ensure_ascii=False, indent=2)
    font = json.dumps(v2["fonts"][PROPORTIONAL_PROFILE], ensure_ascii=False, indent=2)
    return f'''/**
 * GENERATED FILE -- DO NOT EDIT.
 *
 * Produced by `scripts/migrate_atlas_v2.py` from
 * `src/lateletter/garden/data/atlas.v2.json`. Edit the atlas and regenerate;
 * editing this file directly would recreate exactly the split art ownership
 * that moving to the atlas was meant to end.
 *
 * Contains every asset carrying the `{PROPORTIONAL_PROFILE}` profile. Each entry
 * holds the asset's drawing anchor, its cell box, and its states as row strings.
 * Row strings are NOT cell matrices: their on-screen width is measured at
 * runtime by `web/garden-geometry.mjs`, so counting their characters means
 * nothing. See SPEC 7.9.3.
 *
 * Generator version: {v2["generator_version"]}
 * Atlas id: {v2["id"]}
 */

/** The font these row strings were drawn against and must be measured in. */
export const ATLAS_PROPORTIONAL_FONT = Object.freeze({font});

/** Canonical proportional art, keyed by canonical asset id. */
export const ATLAS_PROPORTIONAL_ART = Object.freeze({body});

/**
 * Look up one frame of canonical art by asset id.
 *
 * @param {{string}} assetId - Canonical id, e.g. `fixture.bench`.
 * @param {{string}} [state] - Desired state; falls back to `idle`.
 * @returns {{{{rows: string[], compactRows: string[]|null, anchor: number[], accents: object|null}}|null}}
 *   The first frame of that state, or null when the atlas does not own this
 *   asset yet, which is how a caller distinguishes an unmigrated asset from one
 *   that genuinely has no art.
 *
 * The wording above is deliberate. The Pages bundler finds imports with a
 * regular expression that does not know about comments, so the word `from`
 * followed by a quoted phrase reads as a real import wherever it appears --
 * including inside prose. An earlier draft of this sentence failed the deploy
 * build on a module named "no art". See FAILURE_LOG.
 */
export function canonicalProportionalArt(assetId, state = 'idle', frame = 0) {{
  const asset = ATLAS_PROPORTIONAL_ART[assetId];
  if (!asset) return null;
  const frames = asset.states[state] ?? asset.states.idle;
  if (!frames || frames.length === 0) return null;
  const cycle = frames.reduce((total, item) => total + Math.max(1, Number(item.ticks) || 1), 0);
  let cursor = ((Math.floor(Number(frame) || 0) % cycle) + cycle) % cycle;
  let selected = frames[0];
  for (const item of frames) {{
    selected = item;
    cursor -= Math.max(1, Number(item.ticks) || 1);
    if (cursor < 0) break;
  }}
  return {{
    rows: selected.rows,
    // Null rather than a copy of `rows`, so the renderer can tell an authored
    // compact drawing from the absence of one and reduce accordingly.
    compactRows: selected.compact_rows ?? null,
    anchor: asset.anchor,
    accents: selected.accents ?? null,
  }};
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source", type=Path,
        default=Path("src/lateletter/garden/data/atlas.v1.json"),
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path("src/lateletter/garden/data/atlas.v2.json"),
    )
    parser.add_argument(
        "--browser-output", type=Path,
        default=Path("web/garden-atlas-art.mjs"),
    )
    args = parser.parse_args()

    v1 = json.loads(args.source.read_text(encoding="utf-8"))
    v2 = migrate(v1)

    # Validate before writing. Emitting an atlas that fails its own compiler
    # would leave a broken file on disk for someone else to discover later.
    from lateletter.garden.atlas import validate_atlas
    validate_atlas(v2)

    args.output.write_text(
        json.dumps(v2, ensure_ascii=False, indent=2) + "\n", encoding="utf-8",
    )
    args.browser_output.write_text(emit_browser_art_module(v2), encoding="utf-8")

    owned = [a["id"] for a in v2["assets"] if PROPORTIONAL_PROFILE in a["profiles"]]
    print(f"wrote {args.output} ({len(v2['assets'])} assets)")
    print(f"wrote {args.browser_output}")
    print(f"  atlas-owned proportional assets: {', '.join(owned) or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
